### ISSUE TITLE
Run control environment variables

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/confmodel#44]
Some of the environmnent variables should really _not_ be set at all in the configuration, and only be set by the run control. So, we should leave them blank, and let the run control decide what they are (for example `DUNEDAQ_SESSION`).

**Comment by alessandrothea** [comment]
I suspect we need to be tad more clear about what should and shouldn't be set in configuration.
Let's write some specs, shan't we?

**Comment by plasorak** [comment]
Ok, so here is my proposal:
 - In the unified shell (i.e. drunc developper environment), almost all variables can be overriden at boot, but these variables are _Session-wide_ (i.e. you cannot have individual application custom environment).
 - There are some dynamic variables that are set by the run control (these variables _cannot_ be overriden by the unified shell):
   - `DUNEDAQ_SESSION` (and `DUNEDAQ_PARTITION`): Come from the session name.
   - `DUNEDAQ_APPLICATION_NAME`: application name.
 - There are some variables which the run control sets depending if the configuration (iff the "value" in the configuration is empty), and these could come from the environment:
   - `ERS`es, `TRACE`s and logging
   - `CONNECTION_PORT`: That one is a bit more complicated, because really we want a dynamic port, so the run control tries to find a port free and set that variable.
   - Any other?
 - All the other variables are set in configuration.

**Comment by plasorak** [comment]
Done here: https://github.com/DUNE-DAQ/drunc/pull/250
